In [1]:
!conda install numpy

^C


In [2]:
!conda --version

conda 4.8.3


In [3]:
!conda list numpy

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.5           py38h6530119_0  
numpy-base                1.18.5           py38hc3f5095_0  
numpydoc                  1.1.0                      py_0  


In [4]:
!conda list

^C


In [6]:
!conda list

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12                     py_0  
anaconda                  2020.07                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.9.12                   py38_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py38_0  
asn1crypto                1.3.0                    py38_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.1.post1      py38he774522_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.5.3                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0     

pep8                      1.7.1                    py38_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    7.2.0            py38hcc1f983_0  
pip                       20.1.1                   py38_1  
pkginfo                   1.5.0.1                  py38_0  
pluggy                    0.13.1                   py38_0  
ply                       3.11                     py38_0  
powershell_shortcut       0.0.1                         3  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
psutil                    5.7.0            py38he774522_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py38ha925a31_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3         

In [7]:
import numpy as np

In [8]:
np.__version__

'1.18.5'

In [9]:
#kita pakai Pandas, SciPy, Matplotlib, scikit-learn

## Array

In [12]:
#array 1 tipe data
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
print(arr1[1])
print(arr1[2])
print(arr1[-1])

[4 5 6]
[7 8 9]
[10 11 12]


In [15]:
list1 = ([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #ini list
print (list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [24]:
#ambil anggota di list
print(list1[0][0])
print(list1[0][2])
print(list1[1][0])

1
3
4


In [30]:
print(arr1[0,0])
print(arr1[0])
print(arr1[1])
print(arr1[:,0])   #colomn

1
[1 2 3]
[4 5 6]
[ 1  4  7 10]


In [31]:
print(arr1[:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
arr1.dtype

dtype('int32')

In [33]:
type(arr1)

numpy.ndarray

In [35]:
arr2= np.array([[.1,.2],[.3,.4]])
print(arr2)
arr2.dtype

[[0.1 0.2]
 [0.3 0.4]]


dtype('float64')

In [39]:
arr3= np.array([
    [
        [1,2,3],
        [11,22,33]
    ],
    [
        [4,5,6],
        [44,55,66]
    ]
])
print(arr3)

[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [40]:
# shape of array
print('shape of arr1:', arr1.shape)
print('shape of arr2:', arr2.shape)
print('shape of arr3:', arr3.shape)

print('dimension of arr1:', arr1.ndim)
print('dimension of arr2:', arr2.ndim)
print('dimension of arr3:', arr3.ndim)

shape of arr1: (4, 3)
shape of arr2: (2, 2)
shape of arr3: (2, 2, 3)
dimension of arr1: 2
dimension of arr2: 2
dimension of arr3: 3


In [45]:
arr_zeros_1 = np.zeros(10)
arr_zeros_2 = np.zeros((10,5))
arr_zeros_3 = np.zeros([5,10,10])
                       
print(arr_zeros_1, arr_zeros_1.shape) 
print('--')
print(arr_zeros_2, arr_zeros_2.shape)
print('--')
print(arr_zeros_3, arr_zeros_3.shape)
print('--')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
--
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (10, 5)
--
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 

In [50]:
arr_ones_1 = np.ones(10)  #bikin array isinya 1
arr_ones_2 = np.ones((10,5)) #bikin array shape (,)
arr_ones_3 = np.ones([5,10,10]) #bikin array dimensi
                       
print(arr_ones_1, arr_ones_1.shape) 
print('--')
print(arr_ones_2, arr_ones_2.shape)
print('--')
print(arr_ones_3, arr_ones_3.shape)
print('--')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
--
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (10, 5)
--
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 

In [59]:
arr_empty = np.empty((3,2)) #buat array random shape (,)
print(arr_empty)
arr_empty.dtype

[[0. 0.]
 [0. 0.]
 [0. 0.]]


dtype('float64')

In [61]:
print(np.arange(0,100,2)) #(start index, sampe index exclude, increment)
print(np.arange(10))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[0 1 2 3 4 5 6 7 8 9]


In [64]:
arr_one = np.array([1,2,3,4,5])
arr_one

array([1, 2, 3, 4, 5])

In [65]:
np.append(arr_one,10) #untuk nambah array

array([ 1,  2,  3,  4,  5, 10])

In [67]:
np.append(arr_one,[6,7,8,9,10],axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
np.append(arr1,[[13,14,15]],axis=0) #axis itu dimensi 0,1,2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [77]:
np.delete(arr1, 0, axis=0) #nama array,index, dimensi

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
#array sort
#np.sort(nama array,dimensi)



In [81]:
#reshape asal jumlah sama, shape itu (baris, colomn)
#shape (baris, colomn, dimensi)??
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
arr1.shape

(4, 3)

In [88]:
np.reshape(arr1,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
np.reshape(arr1,(1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [89]:
np.reshape(arr1,(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [90]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
arr1[arr1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [92]:
arr1[(arr1>5) & (arr1 % 2 == 0)] #and pake &, or pake |

array([ 6,  8, 10, 12])

In [93]:
arr1[(arr1>5) | (arr1 % 3 == 0)]

array([ 3,  6,  7,  8,  9, 10, 11, 12])

In [95]:
#math operational statistik
arr11=arr1*10
print(arr11)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [98]:
print(arr1+arr11)
print(arr1.dot(arr11.T)) #T= transpose

[[ 11  22  33]
 [ 44  55  66]
 [ 77  88  99]
 [110 121 132]]
[[ 140  320  500  680]
 [ 320  770 1220 1670]
 [ 500 1220 1940 2660]
 [ 680 1670 2660 3650]]


In [103]:
print(arr1.sum())
print(arr1.mean())

78
6.5
